#!/bin/sh
set -x

./install-neobundle.sh
ln -s ~/Documents/dotfiles/gitconfig ~/.gitconfig
ln -s ~/Documents/dotfiles/vimrc ~/.vimrc
ln -s ~/Documents/dotfiles/gvimrc ~/.gvimrc
ln -s ~/Documents/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/Documents/dotfiles/byobu.conf ~/.byobu/.tmux.conf
ln -s ~/Documents/dotfiles/zshrc ~/.zshrc
ln -s ~/Documents/dotfiles/bin ~/bin

